### ISSUE TITLE
hexo博客icarus主题的布局跟宽度的问题

### ISSUE THREAD

**Issue by Didudia** [Zhounning/Zhounning.github.io#1]
您好，我是自从icarus主题，那边的issue找过来的，想请教一下：主页三栏，文章两栏布局的情况下，主页和文章的整个页面的宽度如何拓宽？

**Comment by bugcat9** [comment]
这个主题我好久没用了都忘记了🤣，不好意思我只记得当时就是对于那个几个和栏数和宽度相关的参数进行调节就行
